[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
digital_nomad_exchange = "D4JCMSe8bh1GcuPyGjicJ4JbdcmWmAPLvcuDqgpVSWFB"
dne_factory = "F4GTZaky3u6tNQBmYEEzPbpSCVPaKc3ZYjzVpM8NEx3Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
