[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
digital_nomad_exchange = "EkZNT5WirgZyKxVbrPaRV6GM53AXTjiv6HmNt98wBjNM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ./tests/**/*.ts"
create_pool = "ts-node ./scripts/createNewPool.ts"